CFLAGS=-Wall -O2 -g

Test20161031_sensor: Test20161031_sensor.c
	/home/fujii/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -g $(CFLAGS) $(LDFLAGS) $< -o $@ 
clean:
	rm -f Test20161031_sensor Test20161031_sensor.o

